#LucaMoneyManager - Impostazioni
#https://github.com/lucaa/moneymanager
#Thu Mar 26 06:15:03 CET 2026
accounts.favorites_only=0
accounts.type_order=["checking","credit","cash","savings","investment"]
analytics.months=3
appearance.theme=dark
backup.dir=D\:\\LucaMoneyManager
backup.enabled=0
db.path=D\:\\LucaMoneyManager\\luca.db
portfolio.active_only=0
proj.mode=monthly
proj.months=1
proj.range=1y
tx.range=14d
