#LucaMoneyManager - Impostazioni
#https://github.com/lucaa/moneymanager
#Thu Apr 02 06:37:26 CEST 2026
accounts.favorites_only=0
accounts.type_order=["checking","credit","cash","savings","investment"]
analytics.excludeCurrent=1
analytics.months=3
appearance.custom_themes=[]
appearance.theme=dark
attachments.dir=D\:\\LucaMoneyManager\\allegati
backup.dir=C\:\\Users\\lucaa\\OneDrive\\Documents\\Luca_Money_Manager\\backups
backup.enabled=0
db.path=D\:\\LucaMoneyManager\\luca.db
portfolio.active_only=0
proj.mode=monthly
proj.months=1
proj.range=1y
tx.range=-3W..0D
